<?php

function backendfootermenu_init() {
  drupal_add_js(drupal_get_path('module', 'backendfootermenu') . '/js/script.js');
  drupal_add_css(drupal_get_path('module', 'backendfootermenu') . '/css/crm_addition.css');
  drupal_add_js(drupal_get_path('module', 'backendfootermenu') . '/js/jquery-1.11.1.js');
  drupal_add_js(drupal_get_path('module', 'backendfootermenu') . '/js/slidx.js');
  drupal_add_js(drupal_get_path('module', 'backendfootermenu') . '/js/noconflict-1.11.1.js'); 
}

function backendfootermenu_permission() {
  return array(
    'access quick add menu' => array(
      'title' => t('Access Quick Add Menu'),
    ),
  );
}

/*
  hook_block_info();
*/

function backendfootermenu_block_info(){
  $blocks['backendfootermenu'] = array(
    'info' => t('Footer Menu'),
    'status' => TRUE,
    'region' => 'footer',
    );
  return $blocks;
}

function backendfootermenu_block_view($delta = '') {
  if(user_access('access quick add menu')) {
          $block = array();
          $out = '';
          $item = menu_get_item();
          $tree = menu_tree_all_data(variable_get('menu_main_links_source', 'navigation'), $item, 3);
          $menu = menu_tree_output($tree);
          $out .= '<a id="slidx-button">Quick Add Content</a>';
          $out .= '<div class="slidx-menu">';
          $i = 0;
          foreach ($menu[6]['#below'] as $key => $value) {
            if(is_numeric($key)){
              $active = '/'.$value['#href'] == request_uri()?'active':'';
              $first = $i==0 ?'first"':'';
              //$items[] = '<a'.$active.' href="/'.$value['#href'].'"> Add '.$value['#title'].' </a>';
              $out .= '<a class="'.$active.' '.$first.'" href="/'.$value['#href'].'"> Add '.$value['#title'].' </a>';
            }
           $i++;  
          }
          $out .= '</div>';
          switch ($delta) {
            case 'backendfootermenu':   
              //$block['content']  = implode('<span style="color:#ccc;">|</span> ', $items);
              $block['content']  = $out;
              break;
          }
          return $block;
         }
}
?>